interface DependencyInfo {
    name: string;
    installed: boolean;
    path: string;
    version: string;
}

interface SubtitleInfo {
    code: string;
    name: string;
    type: 'manual' | 'auto';
}

interface ElectronAPI {
    chooseFolder: () => Promise<string | null>;
    runCommand: (args: string[]) => Promise<{
        success: boolean;
        cancelled: boolean;
        code: number;
        output: string;
        error?: string;
    }>;
    onProgress: (callback: (progress: string) => void) => () => void;
    checkAppUpdate: () => Promise<{
        error?: boolean;
        hasUpdate?: boolean;
        version?: string;
        releaseNotes?: string;
        message?: string;
    }>;
    getCurrentVersion: () => Promise<string>;
    isAutoUpdaterSupported: () => Promise<boolean>;
    reEncodeToMp4: (downloadFolder: string, videoId: string) => Promise<{
        success: boolean;
        cancelled: boolean;
        message: string;
        tmpFiles: string[];
        error?: string;
    }>;
    openExternal: (url: string) => Promise<boolean>;
    checkDependencies: () => Promise<{
        success: boolean;
        allInstalled?: boolean;
        dependencies?: DependencyInfo[];
        missing?: string[];
        platform?: string;
        message?: string;
    }>;
    installMissingDependencies: (options?: { installHomebrew?: boolean }) => Promise<{
        success: boolean;
        installed?: string[];
        failed?: string[];
        message?: string;
        dependencies?: DependencyInfo[];
        details?: Record<string, unknown>;
    }>;
    listSubtitles: (url: string, browser: string, proxy: string) => Promise<{
        success: boolean;
        error: boolean;
        message: string;
        subtitles: SubtitleInfo[];
        isAutoGenerated: boolean;
    }>;
    downloadWithHardsub: (options: {
        url: string;
        browser: string;
        downloadFolder: string;
        subtitleLang: string;
        subtitleType: string;
        codec: string;
        proxy: string;
    }) => Promise<{
        success: boolean;
        cancelled: boolean;
        message: string;
        tmpFiles: string[];
        error?: string;
    }>;
    cancelCommand: () => Promise<{
        success: boolean;
        message: string;
        cancelledTaskId?: string | null;
    }>;
    deleteTemporaryFiles: (paths: string[]) => Promise<void>;
    getFormatInfo: (args: string[]) => Promise<{ ok: boolean; output: string; error: string }>;
    getSettings: () => Promise<Record<string, any>>;
    setSettings: (updates: Record<string, any>) => Promise<Record<string, any>>;
}

interface Window {
    electronAPI: ElectronAPI;
    chooseFolder: () => Promise<void>;
    checkUpdate: () => Promise<void>;
    checkDependencies: () => Promise<void>;
    runCommand: () => Promise<void>;
}
